### ISSUE TITLE
Crash in CIFAR10 tutorial

### ISSUE THREAD

**Issue by OmerRochman** [probabilists/azula#11]
### Description

`sampler = DDIMSampler(averaged, steps=1).to(device)` tries to access `.schedule`, which is an attribute of `denoiser` but not of `AveragedModel`.

### Reproduce

Run the notebook.

### Expected behavior

Should not crash

### Causes and solution

`averaged.schedule = VPSchedule()` is a possible solution.

### Environment

* Azula version: `0.2.0`
* PyTorch version: `2.4.0+cu121`
* Python version: `Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux`
* OS: 
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.6 (Ootpa)
Release:	8.6
Codename:	Ootpa
```

**Comment by francois-rozet** [comment]
Hello @OmerRochman, thank you for the reporting this bug! I thought that `averaged` was simply a copy of `denoiser` but it is actually a wrapper around a copy 😅 The copy is the attribute `.module`. The following should work:

```python
sampler = DDIMSampler(averaged.module, steps=64).to(device)
```

Can you tell me if this fixes the issue?

**Comment by OmerRochman** [comment]
Indeed, thanks!

**Comment by francois-rozet** [comment]
Thanks I'll update the tutorial!
